/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dvornykv' at '3/7/14 3:11 PM' with Gradle 1.10
 *
 * @author dvornykv, @date 3/7/14 3:11 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
